// Complete list of 196 countries with flags
const COUNTRIES = [
    { code: 'ad', phone: '+376', name: 'Andorra' },
    { code: 'ae', phone: '+971', name: 'United Arab Emirates' },
    { code: 'af', phone: '+93', name: 'Afghanistan' },
    { code: 'ag', phone: '+1', name: 'Antigua and Barbuda' },
    { code: 'al', phone: '+355', name: 'Albania' },
    { code: 'am', phone: '+374', name: 'Armenia' },
    { code: 'ao', phone: '+244', name: 'Angola' },
    { code: 'ar', phone: '+54', name: 'Argentina' },
    { code: 'at', phone: '+43', name: 'Austria' },
    { code: 'au', phone: '+61', name: 'Australia' },
    { code: 'az', phone: '+994', name: 'Azerbaijan' },
    { code: 'ba', phone: '+387', name: 'Bosnia and Herzegovina' },
    { code: 'bb', phone: '+1', name: 'Barbados' },
    { code: 'bd', phone: '+880', name: 'Bangladesh' },
    { code: 'be', phone: '+32', name: 'Belgium' },
    { code: 'bf', phone: '+226', name: 'Burkina Faso' },
    { code: 'bg', phone: '+359', name: 'Bulgaria' },
    { code: 'bh', phone: '+973', name: 'Bahrain' },
    { code: 'bi', phone: '+257', name: 'Burundi' },
    { code: 'bj', phone: '+229', name: 'Benin' },
    { code: 'bn', phone: '+673', name: 'Brunei' },
    { code: 'bo', phone: '+591', name: 'Bolivia' },
    { code: 'br', phone: '+55', name: 'Brazil' },
    { code: 'bs', phone: '+1', name: 'Bahamas' },
    { code: 'bt', phone: '+975', name: 'Bhutan' },
    { code: 'bw', phone: '+267', name: 'Botswana' },
    { code: 'by', phone: '+375', name: 'Belarus' },
    { code: 'bz', phone: '+501', name: 'Belize' },
    { code: 'ca', phone: '+1', name: 'Canada' },
    { code: 'cd', phone: '+243', name: 'Congo (DRC)' },
    { code: 'cf', phone: '+236', name: 'Central African Republic' },
    { code: 'cg', phone: '+242', name: 'Congo (Republic)' },
    { code: 'ch', phone: '+41', name: 'Switzerland' },
    { code: 'ci', phone: '+225', name: 'Côte d\'Ivoire' },
    { code: 'cl', phone: '+56', name: 'Chile' },
    { code: 'cm', phone: '+237', name: 'Cameroon' },
    { code: 'cn', phone: '+86', name: 'China' },
    { code: 'co', phone: '+57', name: 'Colombia' },
    { code: 'cr', phone: '+506', name: 'Costa Rica' },
    { code: 'cu', phone: '+53', name: 'Cuba' },
    { code: 'cv', phone: '+238', name: 'Cape Verde' },
    { code: 'cy', phone: '+357', name: 'Cyprus' },
    { code: 'cz', phone: '+420', name: 'Czech Republic' },
    { code: 'de', phone: '+49', name: 'Germany' },
    { code: 'dj', phone: '+253', name: 'Djibouti' },
    { code: 'dk', phone: '+45', name: 'Denmark' },
    { code: 'dm', phone: '+1', name: 'Dominica' },
    { code: 'do', phone: '+1', name: 'Dominican Republic' },
    { code: 'dz', phone: '+213', name: 'Algeria' },
    { code: 'ec', phone: '+593', name: 'Ecuador' },
    { code: 'ee', phone: '+372', name: 'Estonia' },
    { code: 'eg', phone: '+20', name: 'Egypt' },
    { code: 'er', phone: '+291', name: 'Eritrea' },
    { code: 'es', phone: '+34', name: 'Spain' },
    { code: 'et', phone: '+251', name: 'Ethiopia' },
    { code: 'fi', phone: '+358', name: 'Finland' },
    { code: 'fj', phone: '+679', name: 'Fiji' },
    { code: 'fr', phone: '+33', name: 'France' },
    { code: 'ga', phone: '+241', name: 'Gabon' },
    { code: 'gb', phone: '+44', name: 'United Kingdom' },
    { code: 'gd', phone: '+1', name: 'Grenada' },
    { code: 'ge', phone: '+995', name: 'Georgia' },
    { code: 'gh', phone: '+233', name: 'Ghana' },
    { code: 'gm', phone: '+220', name: 'Gambia' },
    { code: 'gn', phone: '+224', name: 'Guinea' },
    { code: 'gq', phone: '+240', name: 'Equatorial Guinea' },
    { code: 'gr', phone: '+30', name: 'Greece' },
    { code: 'gt', phone: '+502', name: 'Guatemala' },
    { code: 'gw', phone: '+245', name: 'Guinea-Bissau' },
    { code: 'gy', phone: '+592', name: 'Guyana' },
    { code: 'hk', phone: '+852', name: 'Hong Kong' },
    { code: 'hn', phone: '+504', name: 'Honduras' },
    { code: 'hr', phone: '+385', name: 'Croatia' },
    { code: 'ht', phone: '+509', name: 'Haiti' },
    { code: 'hu', phone: '+36', name: 'Hungary' },
    { code: 'id', phone: '+62', name: 'Indonesia' },
    { code: 'ie', phone: '+353', name: 'Ireland' },
    { code: 'il', phone: '+972', name: 'Israel' },
    { code: 'in', phone: '+91', name: 'India' },
    { code: 'iq', phone: '+964', name: 'Iraq' },
    { code: 'ir', phone: '+98', name: 'Iran' },
    { code: 'is', phone: '+354', name: 'Iceland' },
    { code: 'it', phone: '+39', name: 'Italy' },
    { code: 'jm', phone: '+1', name: 'Jamaica' },
    { code: 'jo', phone: '+962', name: 'Jordan' },
    { code: 'jp', phone: '+81', name: 'Japan' },
    { code: 'ke', phone: '+254', name: 'Kenya' },
    { code: 'kg', phone: '+996', name: 'Kyrgyzstan' },
    { code: 'kh', phone: '+855', name: 'Cambodia' },
    { code: 'km', phone: '+269', name: 'Comoros' },
    { code: 'kn', phone: '+1', name: 'Saint Kitts and Nevis' },
    { code: 'kp', phone: '+850', name: 'North Korea' },
    { code: 'kr', phone: '+82', name: 'South Korea' },
    { code: 'kw', phone: '+965', name: 'Kuwait' },
    { code: 'kz', phone: '+7', name: 'Kazakhstan' },
    { code: 'la', phone: '+856', name: 'Laos' },
    { code: 'lb', phone: '+961', name: 'Lebanon' },
    { code: 'lc', phone: '+1', name: 'Saint Lucia' },
    { code: 'li', phone: '+423', name: 'Liechtenstein' },
    { code: 'lk', phone: '+94', name: 'Sri Lanka' },
    { code: 'lr', phone: '+231', name: 'Liberia' },
    { code: 'ls', phone: '+266', name: 'Lesotho' },
    { code: 'lt', phone: '+370', name: 'Lithuania' },
    { code: 'lu', phone: '+352', name: 'Luxembourg' },
    { code: 'lv', phone: '+371', name: 'Latvia' },
    { code: 'ly', phone: '+218', name: 'Libya' },
    { code: 'ma', phone: '+212', name: 'Morocco' },
    { code: 'mc', phone: '+377', name: 'Monaco' },
    { code: 'md', phone: '+373', name: 'Moldova' },
    { code: 'me', phone: '+382', name: 'Montenegro' },
    { code: 'mg', phone: '+261', name: 'Madagascar' },
    { code: 'mk', phone: '+389', name: 'North Macedonia' },
    { code: 'ml', phone: '+223', name: 'Mali' },
    { code: 'mm', phone: '+95', name: 'Myanmar' },
    { code: 'mn', phone: '+976', name: 'Mongolia' },
    { code: 'mo', phone: '+853', name: 'Macau' },
    { code: 'mr', phone: '+222', name: 'Mauritania' },
    { code: 'mt', phone: '+356', name: 'Malta' },
    { code: 'mu', phone: '+230', name: 'Mauritius' },
    { code: 'mv', phone: '+960', name: 'Maldives' },
    { code: 'mw', phone: '+265', name: 'Malawi' },
    { code: 'mx', phone: '+52', name: 'Mexico' },
    { code: 'my', phone: '+60', name: 'Malaysia' },
    { code: 'mz', phone: '+258', name: 'Mozambique' },
    { code: 'na', phone: '+264', name: 'Namibia' },
    { code: 'ne', phone: '+227', name: 'Niger' },
    { code: 'ng', phone: '+234', name: 'Nigeria' },
    { code: 'ni', phone: '+505', name: 'Nicaragua' },
    { code: 'nl', phone: '+31', name: 'Netherlands' },
    { code: 'no', phone: '+47', name: 'Norway' },
    { code: 'np', phone: '+977', name: 'Nepal' },
    { code: 'nz', phone: '+64', name: 'New Zealand' },
    { code: 'om', phone: '+968', name: 'Oman' },
    { code: 'pa', phone: '+507', name: 'Panama' },
    { code: 'pe', phone: '+51', name: 'Peru' },
    { code: 'pg', phone: '+675', name: 'Papua New Guinea' },
    { code: 'ph', phone: '+63', name: 'Philippines' },
    { code: 'pk', phone: '+92', name: 'Pakistan' },
    { code: 'pl', phone: '+48', name: 'Poland' },
    { code: 'pr', phone: '+1', name: 'Puerto Rico' },
    { code: 'ps', phone: '+970', name: 'Palestine' },
    { code: 'pt', phone: '+351', name: 'Portugal' },
    { code: 'py', phone: '+595', name: 'Paraguay' },
    { code: 'qa', phone: '+974', name: 'Qatar' },
    { code: 'ro', phone: '+40', name: 'Romania' },
    { code: 'rs', phone: '+381', name: 'Serbia' },
    { code: 'ru', phone: '+7', name: 'Russia' },
    { code: 'rw', phone: '+250', name: 'Rwanda' },
    { code: 'sa', phone: '+966', name: 'Saudi Arabia' },
    { code: 'sb', phone: '+677', name: 'Solomon Islands' },
    { code: 'sc', phone: '+248', name: 'Seychelles' },
    { code: 'sd', phone: '+249', name: 'Sudan' },
    { code: 'se', phone: '+46', name: 'Sweden' },
    { code: 'sg', phone: '+65', name: 'Singapore' },
    { code: 'si', phone: '+386', name: 'Slovenia' },
    { code: 'sk', phone: '+421', name: 'Slovakia' },
    { code: 'sl', phone: '+232', name: 'Sierra Leone' },
    { code: 'sm', phone: '+378', name: 'San Marino' },
    { code: 'sn', phone: '+221', name: 'Senegal' },
    { code: 'so', phone: '+252', name: 'Somalia' },
    { code: 'sr', phone: '+597', name: 'Suriname' },
    { code: 'ss', phone: '+211', name: 'South Sudan' },
    { code: 'sv', phone: '+503', name: 'El Salvador' },
    { code: 'sy', phone: '+963', name: 'Syria' },
    { code: 'sz', phone: '+268', name: 'Eswatini' },
    { code: 'td', phone: '+235', name: 'Chad' },
    { code: 'tg', phone: '+228', name: 'Togo' },
    { code: 'th', phone: '+66', name: 'Thailand' },
    { code: 'tj', phone: '+992', name: 'Tajikistan' },
    { code: 'tl', phone: '+670', name: 'Timor-Leste' },
    { code: 'tm', phone: '+993', name: 'Turkmenistan' },
    { code: 'tn', phone: '+216', name: 'Tunisia' },
    { code: 'to', phone: '+676', name: 'Tonga' },
    { code: 'tr', phone: '+90', name: 'Turkey' },
    { code: 'tt', phone: '+1', name: 'Trinidad and Tobago' },
    { code: 'tw', phone: '+886', name: 'Taiwan' },
    { code: 'tz', phone: '+255', name: 'Tanzania' },
    { code: 'ua', phone: '+380', name: 'Ukraine' },
    { code: 'ug', phone: '+256', name: 'Uganda' },
    { code: 'us', phone: '+1', name: 'United States' },
    { code: 'uy', phone: '+598', name: 'Uruguay' },
    { code: 'uz', phone: '+998', name: 'Uzbekistan' },
    { code: 'va', phone: '+39', name: 'Vatican City' },
    { code: 'vc', phone: '+1', name: 'Saint Vincent and the Grenadines' },
    { code: 've', phone: '+58', name: 'Venezuela' },
    { code: 'vn', phone: '+84', name: 'Vietnam' },
    { code: 'vu', phone: '+678', name: 'Vanuatu' },
    { code: 'ws', phone: '+685', name: 'Samoa' },
    { code: 'xk', phone: '+383', name: 'Kosovo' },
    { code: 'ye', phone: '+967', name: 'Yemen' },
    { code: 'za', phone: '+27', name: 'South Africa' },
    { code: 'zm', phone: '+260', name: 'Zambia' },
    { code: 'zw', phone: '+263', name: 'Zimbabwe' }
];

// Generate HTML for country dropdown
function generateCountryOptions() {
    return COUNTRIES.map(country => `
                                    <div class="country-option${country.code === 'vn' ? ' selected' : ''}" data-code="${country.phone}" data-flag="images/flags/${country.code}.png" onclick="selectCountry('${country.phone}', 'images/flags/${country.code}.png', '${country.name.replace(/'/g, "\\'")}')">
                                        <img src="images/flags/${country.code}.png" alt="${country.name}" />
                                        <span class="country-name">${country.name}</span>
                                        <span class="country-code-text">${country.phone}</span>
                                    </div>`).join('');
}
